#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

usage() {
  cat <<'EOF'
Usage: scripts/leonardo/00_write_runtime_env.sh

Writes scripts/leonardo/env.sh with cache, data, and offline-ready runtime
variables. Run this on the login node before downloads and source the generated
file in Slurm jobs before launching training.

Useful overrides:
  DPLM_INSTALL_ROOT      Shared persistent root. Default: ${SCRATCH:-${WORK:-$HOME}}/dplm_reproduce
  DPLM_CACHE_ROOT        Cache root. Default: $DPLM_INSTALL_ROOT/cache
  DPLM_DATA_DIR          Data root. Default: ./data-bin
  DPLM_CONDA_ACTIVATE    Conda activate path. Default: /home/cherry/miniconda/bin/activate
  DPLM_CONDA_ENV         Conda env name. Default: dplm
  DPLM_ENV_FILE          Output env file. Default: scripts/leonardo/env.sh
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

ensure_dirs
mkdir -p "$(dirname "${DPLM_ENV_FILE}")"

cat > "${DPLM_ENV_FILE}" <<EOF
#!/usr/bin/env bash
# Generated by scripts/leonardo/00_write_runtime_env.sh.
# Source this file on both Leonardo login and compute nodes.

export PROJECT_ROOT="${ROOT_DIR}"
export DPLM_CONDA_ACTIVATE="${DPLM_CONDA_ACTIVATE}"
export DPLM_CONDA_ENV="${DPLM_CONDA_ENV}"
export DPLM_INSTALL_ROOT="${DPLM_INSTALL_ROOT}"
export DPLM_CACHE_ROOT="${DPLM_CACHE_ROOT}"
export DPLM_DATA_DIR="${DPLM_DATA_DIR}"
export DPLM_LOG_DIR="${DPLM_LOG_DIR}"

export HF_HOME="${DPLM_CACHE_ROOT}/huggingface"
export HF_HUB_CACHE="\${HF_HOME}/hub"
export HF_DATASETS_CACHE="\${HF_HOME}/datasets"
export TRANSFORMERS_CACHE="\${HF_HOME}/transformers"
export TORCH_HOME="${DPLM_CACHE_ROOT}/torch"
export TRITON_CACHE_DIR="${DPLM_CACHE_ROOT}/triton"
export MPLCONFIGDIR="${DPLM_CACHE_ROOT}/matplotlib"
export XDG_CACHE_HOME="${DPLM_CACHE_ROOT}/xdg"

export TOKENIZERS_PARALLELISM=false
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export OMP_NUM_THREADS="\${OMP_NUM_THREADS:-8}"
EOF

chmod +x "${DPLM_ENV_FILE}"
ok "wrote ${DPLM_ENV_FILE}"
print_context
